baseURL = "http://aeeooto.github.io/pindery/"
languageCode = "en-us"
title = "Pindery | An amazing party app."
theme = 'elate'


[params]
  
  # custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "AEEooTo"
  description = "An amazing party app."
  email = "edoardo.m.debenedetti@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Pindery"
    home = "Home"
    # work = "Work"
    testimonials = "Testimonials"
    services = "Features"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/doc"
      name = "Docs"
      weight = 10
  
  # Hero section
  [params.hero]
    logo = "images/logo.png"
    title = "Join and organise party as never before."
    subtitle = 'Pindery is an Android and iOS based social network designed to join and organise parties. Each user will have the possibility to create a new party or join already existing ones nearby.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Organize"
    description = "Organize great parties without the need of managing money and not worring about contacting people!"
    url = "#"
    button = "Get started!"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Join"
    description = "Tired of saturday nights watching Netflix? Join Pindery to take part to the best parties you ever saw!"
    url = "#"
    button = "Download Pindery!"
    icon = "icon-people"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Sponsor"
    description = "Tons of people will see your events and your products while joining or organizing parties. You'll forget those weird sandiwch men!"
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_7.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "What do our users think about Pindery?"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "What can I do with Pindery?"
    description = "Ok, gotcha, it seems great, but how does it actually work?"

    [[params.services.item]]
      title = "Find and join parties"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-search"

    [[params.services.item]]
      title = "Organise parties without managing money"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-wrench"

    [[params.services.item]]
      title = "Sponsor your products"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-beer"

      [[params.services.item]]
      title = "Promote your venue"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-bar-graph2"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "AEEooTo: Anna, Edoardo, Edoardo (in Torino). A great project team. Meet us!"

    [[params.about.item]]
      name = "Anna Tranquillini"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Edoardo Debenedetti"
      position = "Flutter developer"
      description = "Computer Engineering student @ PoliTo, exchanging @ Tongji University in Shanghai | IT Consultant & PM @ J.E.To.P."
      img = "/about/edoardo-debenedetti.jpg"
      alt = "Edoardo Debenedetti"
      social = [
        ["icon-twitter", "http://twitter.com/edoardo_debe"],
        ["icon-instagram", "https://www.instagram.com/edoardo.debenedetti/"],
        ["icon-linkedin", "https://linkedin.com/in/edoardo-debenedetti"],
        ["icon-compass", "https://edoardodebenedetti.me"],
        ["icon-github", "https://github.com/dedeswim"]
      ]

    [[params.about.item]]
      name = "Edoardo Ghignone"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Some really random cool numbers"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 1
      interval = 1
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code (that's real!)"
      icon = "icon-code"
      from = 0
      to = 191855
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 120
      interval = 40
      speed = 5000

    [[params.counters.item]]
      description = "Organised parties"
      icon = "icon-people"
      from = 0
      to = 2
      interval = 1
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Do you have any kind of questions about Pindery? Let us know!"
    
    # Available icons: http://simplelineicons.com/
    details = [
        # ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        # ["icon-phone", "(123) 465-6789"],
        # ["icon-envelope", "info@freehtml5.co"],
        # ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; AEEooTo. All Rights Reserved. <br>Created by us, based on a theme by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    # links = [
    #     ["icon-twitter", "#twitter"],
    #     ["icon-facebook", "#facebook"],
    #     ["icon-youtube", "#youtube"]
    # ]