baseURL = "http://aeeooto.github.io/pindery/"
languageCode = "en-us"
title = "Pindery | An amazing party app."
theme = 'elate'


[params]
  
  # custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "AEEooTo"
  description = "An amazing party app."
  email = "edoardo.m.debenedetti@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Pindery"
    home = "Home"
    intro = "Download"
    # work = "Work"
    testimonials = "Testimonials"
    services = "Features"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/doc"
      name = "Docs"
      weight = 10
  
  # Hero section
  [params.hero]
    logo = "images/logo.png"
    title = "Join and organise party as never before."
    subtitle = 'Pindery is an Android and iOS based social network designed to join and organise parties. Each user will have the possibility to create a new party or join already existing ones nearby.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
    enable = true

  [[params.intro.item]]
    title = "Organize"
    description = "Organize great parties without the need of managing money and not worring about contacting people!"
    url = "#"
    button = "Get started!"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Join"
    description = "Tired of saturday nights watching Netflix? Join Pindery to take part to the best parties you ever saw!"
    url = "#"
    button = "Download Pindery!"
    icon = "icon-people"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Sponsor"
    description = "Tons of people will see your events and your products while joining or organizing parties. You'll forget those weird sandiwch men!"
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_7.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "fKFbnhcNnjE"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "What do our users think about Pindery?"

    [[params.testimonials.item]]
      quote = "&ldquo;Finding Pindery was one of the best thing that ever happened to me! Since using this app, organizing parties has become so easy and inexpensive that I cannot stop creating new events! The only side effect is that I don’t have time to study anymore.&rdquo;"
      person = 'Jean Doe, student @ Tongji University'
      img = "/testimonials/jean-doe.jpg"
      alt = "Jean Doe"

    [[params.testimonials.item]]
      quote = "&ldquo;As a university student, Pindery gives me the opportunity to find events close to my dorm that I would have never known of in any other way! Last week I ended up in a Mexican themed party just 5 minutes from the university. I only had to bring with me a bottle of tequila and some tacos and enjoy the company – Best time ever!&rdquo;"
      person = 'Mario Rossi, student @ PoliTo'
      img = "/testimonials/mario-rossi.jpg"
      alt = "Mario Rossi"

    [[params.testimonials.item]]
      quote = "&ldquo;As a bar owner finding a good way to advertise without having to hand out fliers around the city was becoming a real struggle! Since I am using Pindery I see week by week an increasing flow of young customers coming to my pub, I just love the whole AEEooTo team for building up such a great platform.&rdquo;"
      person = '李先生, owner of Shanghai Pub'
      img = "/testimonials/li-xian-sheng.jpg"
      alt = "李先生"
    



  # Services section
  [params.services]
    enable = true
    title = "What can I do with Pindery?"
    description = "Ok, gotcha, it seems great, but how does it actually work?"

    [[params.services.item]]
      title = "Find and join parties"
      description = "To join a Party, you just have to choose the one you like more from a selection based on the position, check the info and then choose all the items to bring! A lower threshold needs to be satisfied and it is calculated taking into consideration different parameters such as the total number of participants."
      icon = "icon-search"

    [[params.services.item]]
      title = "Organise parties without managing money"
      description = "To create a Party, you just need to choose what are the items to be brought, and our APP will equally distribute them among all the participants with its smart point system! In addition, it will also send a notification to all the people interested in parties in that zone, reaching everybody at once!"
      icon = "icon-wrench"

    [[params.services.item]]
      title = "Sponsor your products"
      description = "If your business produce a potential Party Item you can partner with us to reach more effectively your customers! Your product will substitute the general item in the catalogue, and then every person that will take part to a party will be encouraged to buy that very item."
      icon = "icon-beer"

      [[params.services.item]]
      title = "Promote your venue"
      description = "If your business is organizing events you can partner with us to promote more effectively your venue! Your event will be in the main page of the APP and every user will see it, either as an alternative or even as a continuation of their Pindery organised party! Choosing this option will route a user towards an external link where he will be able to take part to the event."      
      icon = "icon-bar-graph2"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "**AEEooTo**: **A**nna, **E**doardo, **E**doardo (in **To**rino). A great project team. Meet us!"
    subdescription = "Yes, the central **'o'**s make no sense. We put them just because it sound like *aiuto*, which means *help*, in Italian. Don't worry, it's ironic."

    [[params.about.item]]
      name = "Anna Tranquillini"
      position = "Flutter developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "/about/anna-tranquillini.jpg"
      alt = "Person1"
      social = [
        ["icon-github", "https://github.com/annatranquillini"]
      ]

    [[params.about.item]]
      name = "Edoardo Debenedetti"
      position = "Flutter developer"
      description = "Computer Engineering student @ PoliTo, exchanging @ Tongji University in Shanghai | IT Consultant & PM @ [JEToP](https://jetop.com)"
      img = "/about/edoardo-debenedetti.jpg"
      alt = "Edoardo Debenedetti"
      social = [
        ["icon-twitter", "http://twitter.com/edoardo_debe"],
        ["icon-linkedin", "https://linkedin.com/in/edoardo-debenedetti"],
        ["icon-globe", "https://edoardodebenedetti.me"],
        ["icon-github", "https://github.com/dedeswim"]
      ]

    [[params.about.item]]
      name = "Edoardo Ghignone"
      position = "Flutter developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "/about/edoardo-ghignone.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "http://twitter.com/gnone42"],
        ["icon-linkedin", "https://linkedin.com/in/edoardo-ghignone-355b43149/"],
        ["icon-github", "https://github.com/stephanNorsten"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Some really random cool numbers"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0.5
      to = 0.5
      interval = 0.1
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code (no, that one is not random)"
      icon = "icon-code"
      from = 0
      to = 4750
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 120
      interval = 40
      speed = 5000

    [[params.counters.item]]
      description = "Organised parties"
      icon = "icon-people"
      from = 2
      to = 2
      interval = 1
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Do you have any kind of question about Pindery? Let us know!"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "**Tongji University**, Jiading Campus, SH, China. <br>**Politecnico di Torino**, Torino, Italy."],
        # ["icon-phone", "(123) 465-6789"],
        # ["icon-envelope", "info@freehtml5.co"],
        # ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; AEEooTo. All Rights Reserved. <br>Created by us, based on a theme by [FREEHTML5.co](http://freehtml5.co/).<br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>. Kindly hosted by [GitHub](https://github.com).'
    # links = [
    #     ["icon-twitter", "#twitter"],
    #     ["icon-facebook", "#facebook"],
    #     ["icon-youtube", "#youtube"]
    # ]